spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri:
            http://localhost:8001/
          predicates:
            - Path=/api/users/**
        - id: major
          uri:
            http://localhost:8002/
          predicates:
            - Path=/api/majors/**
        - id: authentication
          uri:
            http://localhost:8003/
          predicates:
            - Path=/api/auth/**
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka